### ISSUE TITLE
Remote control for presentation

### ISSUE THREAD

**Issue by dimfried** [fluster/deckdeckgo#5]
It could be cool to remote control deckdeckgo with your smartphone while having a presentation. One could achieve this for example with WebRTC.

I did not wrap my mind around possible UX and tech issues on creating a WebRTC P2P network ([Presentation] <-> [Remote Control]) but I think this could be a useful and very interesting thing 😄

**Comment by peterpeterparker** [comment]
I've built a proof of concept (using socket.io) and I have some features idea too...so yep I'm on it 😉

**Comment by peterpeterparker** [comment]
I gonna close this issue because there are and might be many new components, apps etc.

The issues and repo to track are:

* For the starter kit: https://github.com/fluster/deckdeckgo-starter/issues/15

* The new project, the new app, the remote control: https://github.com/fluster/deckdeckgo-app

* There might be a new Web Components later on
